In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [419]:
df = pd.read_csv('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\\소상공인시장진흥공단_상가(상권)정보_서울_202106.csv', encoding = 'UTF-8')

In [420]:
df.columns
# df.dropna(subset=['상호명'], inplace = True)

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [421]:
df.상권업종중분류명.value_counts()

한식          43770
이/미용/건강     27678
종합소매점       21370
커피점/카페      20832
의복의류        15042
            ...
종교용품판매         48
놀이/여가/취미       38
스포츠/운동         30
유스호스텔           9
부동산관련서비스        3
Name: 상권업종중분류명, Length: 89, dtype: int64

In [422]:
df.상호명.value_counts()

CU          1707
GS25        1413
세븐일레븐        896
카페           634
이마트          420
            ...
CECICELA       1
뷰티엠바이린         1
온누리슈퍼          1
조오탉            1
솔시카고피자         1
Name: 상호명, Length: 223539, dtype: int64

In [423]:
from tqdm.notebook import tqdm

for i in tqdm(range(len(df.상권업종중분류코드))):
    if df.상권업종중분류코드[i] != 'Q12':
        df.상권업종중분류코드[i] = np.nan
    else:
        pass

  0%|          | 0/316078 [00:00<?, ?it/s]

In [ ]:
df.상권업종중분류코드.value_counts()

Q12    20832
Name: 상권업종중분류코드, dtype: int64

In [ ]:
df.dropna(subset = ['상권업종중분류코드'], inplace = True)

In [ ]:
df.상권업종중분류명.value_counts()

커피점/카페    20832
Name: 상권업종중분류명, dtype: int64

In [ ]:
df.상호명.value_counts()

카페             414
이디야커피          367
스타벅스           331
투썸플레이스         165
커피빈            115
              ...
엘리스파이            1
다다               1
투썸플레이스묵동자이점      1
커피투어             1
벨로샵              1
Name: 상호명, Length: 15019, dtype: int64

In [ ]:
print((df.상호명 == '이디야커피').value_counts())
print((df.상호명 == '커피빈').value_counts())
print((df.상호명 == '스타벅스').value_counts())
print((df.상호명 == '빽다방').value_counts())

False    20465
True       367
Name: 상호명, dtype: int64
False    20717
True       115
Name: 상호명, dtype: int64
False    20501
True       331
Name: 상호명, dtype: int64
False    20742
True        90
Name: 상호명, dtype: int64

In [ ]:
# df.reset_index(inplace = True)
# df.set_index
# del df['level_0']
# del df['index']
df2 = df[['상호명', '지점명', '시도명', '시군구명', '도로명주소']]
df2
df2.head(25)

            상호명          지점명    시도명  시군구명                    도로명주소
0           커피빈  코리아대학로대명거리점  서울특별시   종로구         서울특별시 종로구 대명길 25
1         요거프레소          쌍문점  서울특별시   도봉구          서울특별시 도봉구 도당로 7
2         메머드커피          NaN  서울특별시   마포구       서울특별시 마포구 와우산로 149
3         우성커피숍          NaN  서울특별시   양천구         서울특별시 양천구 오목로 48
4          카페클럽          NaN  서울특별시   송파구      서울특별시 송파구 동남로2길 3-6
5          띵낑커피          NaN  서울특별시   광진구     서울특별시 광진구 아차산로29길 32
6   커피빈코리아낙성대역점     코리아낙성대역점  서울특별시   관악구     서울특별시 관악구 남부순환로 1909
7     홈스테드커피삼청점          삼청점  서울특별시   종로구      서울특별시 종로구 북촌로5가길 24
8         로얄커피숍          NaN  서울특별시   강동구        서울특별시 강동구 천호옛길 65
9        빈트리망원점          망원점  서울특별시   마포구         서울특별시 마포구 망원로 22
10         버블베어          NaN  서울특별시   강서구       서울특별시 강서구 금낭화로 167
11         탐앤탐스      막스앤스펜서점  서울특별시   강남구       서울특별시 강남구 압구정로 152
12        카페그리다          NaN  서울특별시   강남구     서울특별시 강남구 테헤란로69길 14
13        커피안바우          NaN  서울특별시   노원구     서울특별시 노원구 덕릉로60길 252
14       보나비아티제        동부이촌점  서울특별시   용산구        서울특별시 용산구 이촌로 224
15         000간          NaN  서울특별시   종로구    서울특별시 종로구 창신10가길 1-11
16       cafe.C          NaN  서울특별시   용산구        서울특별시 용산구 이촌로 310
17    파란달의커피볶는집          NaN  서울특별시   송파구     서울특별시 송파구 송파대로28길 16
18         터치카페          NaN  서울특별시   강남구     서울특별시 강남구 테헤란로38길 29
19         들꽃누리          NaN  서울특별시  영등포구       서울특별시 영등포구 대림로 183
20    스테이보드게임카페          NaN  서울특별시   관악구       서울특별시 관악구 조원로2길 51
21          커피랩          NaN  서울특별시   마포구     서울특별시 마포구 와우산로29길 14
22    커핀그루나루신천점          신천점  서울특별시   송파구      서울특별시 송파구 올림픽로12길 8
23         에스트로          NaN  서울특별시   도봉구  서울특별시 도봉구 노해로63가길 31-11
24        뽕뜨락카페          NaN  서울특별시   강동구       서울특별시 강동구 올림픽로 763

In [ ]:
df2.상호명[2][:3]

'메머드'

In [ ]:
df2['브랜드명'] = np.nan

<ipython-input-270-4dc3f175b32f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['브랜드명'] = np.nan

In [ ]:
df2.head()

     상호명          지점명    시도명 시군구명                도로명주소 브랜드명 임시정리용
0    커피빈  코리아대학로대명거리점  서울특별시  종로구     서울특별시 종로구 대명길 25  커피빈   커피빈
1  요거프레소          쌍문점  서울특별시  도봉구      서울특별시 도봉구 도당로 7  NaN   요거프
2  메머드커피          NaN  서울특별시  마포구   서울특별시 마포구 와우산로 149  NaN   메머드
3  우성커피숍          NaN  서울특별시  양천구     서울특별시 양천구 오목로 48  NaN   우성커
4   카페클럽          NaN  서울특별시  송파구  서울특별시 송파구 동남로2길 3-6  NaN   카페클

In [ ]:
# str.contain 지정된 내용을 찾는 함수
# df2[df['상호명'] == '스타벅스'] - 내용을 찾는 함수
sb = df2[df2.상호명.str.contains('스타벅스|STARBUCKS', case=False)]
sb

               상호명       지점명    시도명  시군구명                 도로명주소  브랜드명
52            스타벅스    동숭로아트점  서울특별시   종로구     서울특별시 종로구 동숭길 110  스타벅스
86     스타벅스남부터미널2점   남부터미널2점  서울특별시   서초구     서울특별시 서초구 효령로 274  스타벅스
129           스타벅스       당산점  서울특별시  영등포구     서울특별시 영등포구 양평로 64  스타벅스
138           스타벅스     가로수길점  서울특별시   강남구  서울특별시 강남구 논현로175길 94  스타벅스
142    스타벅스미아사거리역점   미아사거리역점  서울특별시   강북구      서울특별시 강북구 도봉로 32  스타벅스
...            ...       ...    ...   ...                   ...   ...
20757         스타벅스  태릉입구역DT점  서울특별시   노원구     서울특별시 노원구 화랑로 469  스타벅스
20774     스타벅스삼성교점      삼성교점  서울특별시   강남구  서울특별시 강남구 영동대로86길 12  스타벅스
20781      스타벅스목동점       목동점  서울특별시   양천구     서울특별시 양천구 목동서로 67  스타벅스
20817         스타벅스    명일이마트점  서울특별시   강동구    서울특별시 강동구 동남로75길 5  스타벅스
20818   스타벅스조선호텔후문       NaN  서울특별시    중구    서울특별시 중구 남대문로7길 19  스타벅스

[489 rows x 6 columns]

In [ ]:
ed = df2[df2.상호명.str.contains('이디야|EDIYA|ediya', case=False)]
ed

              상호명        지점명    시도명  시군구명                  도로명주소 브랜드명
36          이디야커피       신길역점  서울특별시  영등포구    서울특별시 영등포구 영등포로 353  이디야
41          이디야커피       라이프점  서울특별시  영등포구      서울특별시 영등포구 63로 40  이디야
76     이디야커피양재AT점      양재AT점  서울특별시   서초구        서울특별시 서초구 동산로 3  이디야
87          이디야커피        시흥점  서울특별시   금천구      서울특별시 금천구 금하로 750  이디야
162         이디야커피      개봉중앙점  서울특별시   구로구     서울특별시 구로구 개봉로3길 26  이디야
...           ...        ...    ...   ...                    ...  ...
20242       이디야커피   장한평군자초교점  서울특별시  동대문구    서울특별시 동대문구 한천로2길 53  이디야
20358       이디야커피      강남율현점  서울특별시   강남구    서울특별시 강남구 밤고개로21길 8  이디야
20405       이디야커피  신사동고개삼거리점  서울특별시   은평구        서울특별시 은평구 갈현로 1  이디야
20565       이디야커피       양원역점  서울특별시   중랑구  서울특별시 중랑구 양원역로14가길 24  이디야
20787       이디야커피       곰달래점  서울특별시   강서구      서울특별시 강서구 곰달래로 52  이디야

[440 rows x 6 columns]

In [ ]:
bd = df2[df2.상호명.str.contains('빽다방|PAIKSCOFFEE', case=False)]
bd

               상호명       지점명    시도명 시군구명                 도로명주소 브랜드명
304      빽다방공덕새창로점    공덕새창로점  서울특별시  마포구    서울특별시 마포구 새창로 15-1  빽다방
355       빽다방서초우성점     서초우성점  서울특별시  서초구    서울특별시 서초구 사임당로 181  빽다방
948    빽다방중계은행사거리점  중계은행사거리점  서울특별시  노원구   서울특별시 노원구 한글비석로 235  빽다방
1244      빽다방성신여대점     성신여대점  서울특별시  성북구  서울특별시 성북구 동소문로20나길 3  빽다방
1255     빽다방신림역1호점    신림역1호점  서울특별시  관악구  서울특별시 관악구 남부순환로 1592  빽다방
...            ...       ...    ...  ...                   ...  ...
20576          빽다방    화양사거리점  서울특별시  성동구  서울특별시 성동구 아차산로17길 57  빽다방
20647          빽다방     강동구청점  서울특별시  강동구     서울특별시 강동구 성내로3길 1  빽다방
20681          빽다방     홍대거리점  서울특별시  마포구    서울특별시 마포구 어울마당로 75  빽다방
20697          빽다방   신용산해링턴점  서울특별시  용산구     서울특별시 용산구 서빙고로 17  빽다방
20764          빽다방     행당무학점  서울특별시  성동구     서울특별시 성동구 행당로 121  빽다방

[127 rows x 6 columns]

In [ ]:
cb = df2[df2.상호명.str.contains('커피빈|COFFEEBEAN', case=False)] # case는 대소문자 구분할 것인지 결정(false이면 대소문자 구분미실시)
cb

               상호명           지점명    시도명  시군구명                 도로명주소 브랜드명
0              커피빈   코리아대학로대명거리점  서울특별시   종로구      서울특별시 종로구 대명길 25  커피빈
6      커피빈코리아낙성대역점      코리아낙성대역점  서울특별시   관악구  서울특별시 관악구 남부순환로 1909  커피빈
43             커피빈  코리아강남역랭기지타워점  서울특별시   강남구   서울특별시 강남구 테헤란로4길 28  커피빈
44             커피빈      코리아청담성당점  서울특별시   강남구     서울특별시 강남구 삼성로 716  커피빈
45             커피빈      코리아청담에스점  서울특별시   강남구    서울특별시 강남구 압구정로 461  커피빈
...            ...           ...    ...   ...                   ...  ...
18488          커피빈   코리아신촌현대백화점점  서울특별시  서대문구     서울특별시 서대문구 신촌로 83  커피빈
19208   커피빈코리아이태원점       코리아이태원점  서울특별시   용산구    서울특별시 용산구 이태원로 189  커피빈
19276          커피빈    코리아을지로입구역점  서울특별시    중구    서울특별시 중구 남대문로10길 6  커피빈
20138          커피빈           길동별  서울특별시   강동구  서울특별시 강동구 양재대로112길 3  커피빈
20217          커피빈     서초우성아파트앞점  서울특별시   서초구    서울특별시 서초구 사임당로 171  커피빈

[169 rows x 6 columns]

In [ ]:
len(sb), len(ed), len(cb), len(bd)

(489, 440, 169, 127)

In [ ]:
df2.브랜드명.value_counts()

스타벅스    489
이디야     436
커피빈     169
빽다방     125
Name: 브랜드명, dtype: int64

In [13]:
# 전국데이터에서 4개 매장 정보 추출하기
starbucks = pd.DataFrame(columns = ['상호명', '지점명', '시도명', '시군구명', '도로명주소'])
coffeebean = pd.DataFrame(columns = ['상호명', '지점명', '시도명', '시군구명', '도로명주소'])
ediya = pd.DataFrame(columns = ['상호명', '지점명', '시도명', '시군구명', '도로명주소'])
paik = pd.DataFrame(columns = ['상호명', '지점명', '시도명', '시군구명', '도로명주소'])

In [14]:
from glob import glob
from tqdm.notebook import tqdm
for filename in tqdm(glob('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\*.csv')):
    print(filename)
    df = pd.read_csv(filename)
    df = df[df.상권업종중분류코드 == 'Q12']
    df = df[['상호명','지점명','시도명','시군구명','도로명주소']]

    sb = df[df.상호명.str.contains('스타벅스|STARBUCKS', case=False)]
    cb = df[df.상호명.str.contains('커피빈|COFFEEBEAN', case=False)]
    ed = df[df.상호명.str.contains('이디야|EDIYA', case=False)]
    bd = df[df.상호명.str.contains('빽다방|PAIKSCOFFEE', case=False)]

    starbucks = pd.concat([starbucks, sb])
    coffeebean = pd.concat([coffeebean, cb])
    ediya = pd.concat([ediya, ed])
    paik = pd.concat([paik, bd])

  0%|          | 0/17 [00:00<?, ?it/s]

C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_강원_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_경기_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_경남_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_경북_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_광주_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_대구_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_대전_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_부산_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_서울_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_세종_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_울산_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_인천_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_전남_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_전북_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_제주_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_충남_202106.csv
C:\Workspace\python\Data_Science\dataA\Cartogram Practice Data\소상공인시장진흥공단_상가(상권)정보_20210630\소상공인시장진흥공단_상가(상권)정보_충북_202106.csv

In [15]:
starbucks.tail()

        상호명      지점명   시도명     시군구명                     도로명주소
72684  스타벅스     충북대점  충청북도  청주시 서원구     충청북도 청주시 서원구 내수동로 113
73841  스타벅스  청주율량DT점  충청북도  청주시 청원구  충청북도 청주시 청원구 충청대로107번길 8
79073  스타벅스    충주연수점  충청북도      충주시         충청북도 충주시 계명대로 227
79357  스타벅스    충주성서점  충청북도      충주시          충청북도 충주시 예성로 151
84354  스타벅스      NaN  충청북도      음성군       충청북도 음성군 원남면 보천로 65

In [16]:
len(starbucks), len(coffeebean), len(ediya), len(paik)

(1547, 293, 2120, 609)

In [18]:
starbucks.to_csv('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\\결과\\스타벅스.csv', index = False)
coffeebean.to_csv('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\\결과\\커피빈.csv', index = False)
ediya.to_csv('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\\결과\\이디야.csv', index = False)
paik.to_csv('C:\\Workspace\\python\\Data_Science\\dataA\\Cartogram Practice Data\\소상공인시장진흥공단_상가(상권)정보_20210630\\결과\\빽다방.csv', index = False)